language: go
go:
- 1.8.x
branches:
  only:
  - master
  - /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:\-(rc\.[0-9]+)*)?$/
cache:
- directories:
  - $GOPATH/bin
  - $GOPATH/pkg
before_install:
- mkdir -p $HOME/gopath/bin
install:
- export PATH=$PATH:$TRAVIS_BUILD_DIR/vendor/bin:$GOPATH/bin
- make bootstrap
notifications:
  slack:
    secure: TAwHQeZqM9b0I1y1VC80jhbUbCtpk1dgPS+6fQPBppH1Syef4f5rZYaG/NHvruiXPeFuYY0fI1OdWxjIYWQU7GXFGhLI6Ypzf8lpCdMbvoyw2RkUvgW0v/enbNOeOGQxi2RzS0C1mUnQanqK6NSaCxElPVYu1oRfmOnS1wK1i1iTr5iwc6XIrXkRNC4PXxXs7cCfoEisluH9xSYlFdsMRv/efbXVFaTzQEmW/sjrM2WgGiOhgatBFSTWKcCyrjpSpcV9ASq5HT3dd9P4D8++8G/uf+2v4KQ4zT4jhmodV/13RR2JdsRonCU4VRKXgRrdkIKFqt7fXDxBTibaRKkV83k3nE8tfyaCfP4K6Kq4+yUPAXm+nIIjVCQ0iunw5jrT0aD1reouTN3q99BN5ReOTFXJ8EIj8F8AnluD6hRXCj9Ml4SLFtcFjyRVEAY2rgAu68IjjfSShxHyOHwp6Y8NpU1SyfaOGe9NYh1ktkKHE5jLq12sUogMYdTNT2x2hK7wWEofJTEQ4lN9bJvwkf6bsZzhpg4kMdH3eLF9ejTbQdnOX9s3l27si0Pho/O3aIQ1KB28Me3HYhb7Tw+BLuK5ATBMmmnzjye1Z2nrHX8TQbf7gT0J2roR7dscuvgQt3EOKnLalMA9oHAWsuJr8JMSQ/vfw0YVzNQJrtLabkWHRZ8=
deploy:
- provider: script
  script: make release
  skip_cleanup: true
  on:
    tags: true
    repo: manifoldco/manifold-cli
env:
  global:
  - AWS_REGION=us-east-1
  - secure: VRLiHdN1XpEqcplB00KhO77KlfJVgf+Fza7WDkiGpmPtcsq3SbtwHCVGfEgKZm1yrIK8bOJzgnu5nWt9TFefL7ltCKhxtjo9F1ZpYGzQZDW+h/gcDqhHjxuYgLFCRUtHYZ4+UZHFqude20wz5CKk2IHq81Uj2QzU3SnaSz9jRk33OVEIVyUthfAqsBO2qTe7SUmqZUmTjtUIl+h0hLBHSplMMig5FQz8npycCDiJMTLzltBIvhNjbXSBOYdA4BI0s70mMYZEeJN4OPrTjiHtFSyfiQGSQX/B8glY5Am0GIfLsZDuSOF1WzdkGwXfvvNGM3hfT9LkrwAfLcOjUE0wr+qgMZlRl8GVpgybJiRb5dlchBwjhIZu9sTxn9798GYgCSmLUqdplYe4vyebF1CDeh+RB6eGkP08i33hFN4selRiVRaJ2e1MHwot7yTqTHzgLfr1lsxwyI7eI/feeN6LATvR9xICjy9F4GmF3UzmGmAi0ieMiemzeJ29YYjfuflYq643RO2SE8oTgfiYtdPBdiaoQ3Ev2HsPWlYl7K8Le579EQHoX4sqEf88l+Hgbg08aymtb6wcb6v/oaUAMrp8lcHL0Mofqrbq2HX+GyrGAExKHvp4lRf6p3bmDy1ISCZ3AX3J4u2SY06A2qRP8+Ruqo1BUQHur+ttu403Br8Ref8=
  - secure: aB5K3oG3zIM0qjRaTUb3v/rMvEgIl9oh7F6vukd61TPxJuc1SKsI5VeCaBPc1FZZoAR9eW4JRjfyi9MY6BXSN5tnDO0BnvF8AUErNki3yCayY9sq3Sjmi52AhfefRRtoaECl/Ui5nVrNkw7J0f8cGq5XZfCxeOop7UH1TrpAybZc897qGqhoNB1wOTbWYdgtucSF9wbMX7VUAlctMKX4aEhJ2ZOZAVhv2nXTZg2Z/PcjbaEFkZyRQIW8314IsaNKhxG9A6OTCLhMHEkRwmhxC0chR0CBxGnS25hWL32X7lg9yN1cGRJfj9yJHxD3WWHa6uPQHP5eDDBeld8J5aj/a4FEhHBcuweOar02Ya/aBA0jjY9UY5FZBV/HREN3lfSSyTBdhUak0wLg91OWDYHDKSqEQrzyUdS7GiBP5zXTuwnKOkkXeWJPSPfQs7R+qsWKEExJviU0TWRr36cNz1gj2oi0qkYpxfkLizxCPEeRPyVkb2j57N0kp4CWnG4vC3zF67VOfmXzjEGo7PgFkCQKgJ75DHnRWbmChUvBy0dsaASEaA4je/Vt2urYLns2FtGjvics3zbW6nsqbMdEgIkArakGG/fftPIQhpLzZGsgYZR0+cpuLCQdD3Rg/Xf6lmRUFKBP0rCWs4ggPOeH+T3ANzEYCu8SOubwYKPdpWmVo8g=
  - secure: b3QoV1fQ+CYVI5yaY8/6f3omSjnP+IzaT9C+6OSyBLHIi9tLSvVV2pePxJ9pMHWpcsopKAzv1UQYfiPTJ2kaHsPvaDbRyPrVljKGz05ycBq6ltXl13abueILbkOWTp9HMOswpHrdrYcXe2T99kC9c1l+AIt11ZRya047JxRZlUy6miJYl6GuIZ1JuDTNM4bl1c8OYDC2iATVmojcDJm0Wwi7/M+/eLJh5OrrF21KV9+cJ9o62JQYvY0qhSI2Oarw8aozF7GoS6SKKvy1BCTze20EheumjRJktcT3zFdgPJJAz7mKIALrqSGk0CRCvvO+HHXCvuBIp+cNgX4CNcQxy+vAc5sTNPSxqpkgmZmpIDcgOg8yZUuyfNTAyD3PezcO3Si53BckLFLaOIpgowRXtIaHQCjpe/mErxhqOxjLmC31MZII3oOdpDUIFDYBWehYLcjE9nlX+2LjdhfifkzFUmcdOAdbypR4hgWh+e0wzq6KAr/igBCcYrtRhctAKgzakyIsofPWnIf4R4KZ4r8GitiWXOu4RADXW2u7r5wlnYd8sZmFI/gDwYlDWlAQfVHPDHWKAIWpSgKeVs4c62JA+z/odSs5lcpdcEhAVt+3FmHpI85bW8Eod/X7SnBvYN4Fl2ykKyj6EF3N8rgDXH1e/M+2bRoA0d5j9Ujr/iR6FBQ=
