language: go
go:
- 1.8.x
branches:
  only:
  - master
  - /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:\-(rc\.[0-9]+)*)?$/
cache:
- directories:
  - $GOPATH/bin
  - $GOPATH/pkg
before_install:
- mkdir -p $HOME/gopath/bin
install:
- export PATH=$PATH:$TRAVIS_BUILD_DIR/vendor/bin:$GOPATH/bin
- make bootstrap
notifications:
  slack:
    secure: gFg1YHRMvvDjlOxG5LlwkR6FkKKdInt1CAKZV5+/K/1fz7nGmDjMdXWD5tZFMf85s8dQRcaNMEb43pPVgXTIgxP/ZG49GtKhHM26zCZY9nfBUd3drG80UCmg2oFKNzIGdWhU//d8Hvz+1Q/zfc6PvJbb8+RNsNBaUrWPywf48tJtcjjzSB2LOPPpnURuH0yhX90uHifrm4K5Z8qSfbiNgPLiAdOZKINjvY+Gk2WQ7730HZuJmYt6yK/93Snr9xIBntr1UryTugW4UVPO7OKOKTcBqVfeV9EPoacJEHqqJriMDMXJSpYJvXmcWBynY+7WZcctHM5qhlvs/onMQopEnX5cTtSJEGsWv+Cfu5CO8PC47JaXWY92VwzHi+Up317mZGRTdI1uiDiFaUvOE8p9S2CRlpNBDR8Zs1Ah1SZ3FroKHePzu3Q5QbPO/qA5a0EFRygLAJEPYt1c/OUJuMXfJSZrGNEkNYcfl9SDOjJVvCCziccgkzj+6Xm2WsNBXzjSFjGww6Te6iZqrkMkKPcrZ/b8X567Tc/1KmpNjWaHF5HbQ4KqTkhCfQzTbqHzBNy2DumZh5aDcZ3/JYBGRwtK++cGuLiuN5RXBvzFL+O2urP6I2wWZiPnfguo41k5ahcScFdZu1E16CJ58Cvjs5CVRpNcYvzwNir9npoeudqdJsE=
deploy:
- provider: script
  script: make release
  skip_cleanup: true
  on:
    tags: true
    repo: manifoldco/manifold-cli
env:
  global:
  - AWS_REGION=us-east-1
  - secure: BVF6T28ZwLXlmB+y3q3eRUsu8K9JtrkllxEqohij6cIw1m2Vxaig9P9f0IAF1WzF4kmSuEWgQtQL6cfKe6ElYl2+WHsrwiLarL3fBhfkcWVNq9PHzZ1b3ySiVdC98PfJJDzvPWszfR2m7C3Q7F4YGbOFx45Rs62rq5Y494MlmdNlo7TTbbSxtfxsxkJch57DWuv9CWTsTiMQYBNK6gdkFiUCc+DVeRNUPo89C8YRtZEVIUCuZGT/1meBO0Q1HUogZAUPoDz0XV9xXpRgF9yFFXgJ3MVW+B3Dui1sCAEXNfiL3jIZ6gGJyYUJ6z9ybslszHJpAFfD/UiKBqzIYw5n0L4SCag+V5be/3dxQy+esHUlctKtao05xIE2MEe4GKdlyl+AaJpEOW+hmoSqdgZhDE88ddJXGJMcS2nEkFZiUi6SDeNwMJA7+eisv0BTx/RoL96R43UkdtEtCo/9+qkIjSglxXqUnQEytoP2C4bnvCsMOMNLyiCu2ijY87EpasgPMA3b6qZKL0OsR8EXt+2805ocwDMOskN/WOg2WjL85BtwwGRofLVWJGjZ5nXXcUN24GowXuaGgLKIbpGrUB1E3B0eNXsYoYh5KcIqUR8vbY59Q6URNjBJWZ3fyuODXjPN6aWy26PFQSgNmiyw99vneNZPSlWhkKdJBE5yYhJXmOU=
  - secure: 54v1hGJ1ckxpsQHJSCMUmjduvgaYn2MT5zHka+zaRxqyOhnik+N5ZT7QLNNQtUF1cudRjPhmGuhK4zTRDrjyOD/QsE/mytfPSOq7jyF+B4K4uPQ2oWq0v1kQO6QWmjwNXilNzSSy44J66OHOfqBguU7Re2e1mfLh5d+3sTAV4Ejd/BHn2SzsMlLh5PEpP8MzeyJK8Q1W0GkSJAInSKfMpjpJjEASXSMdsw3xogPYyPqO0x4K9S9poYUvOY06lEvfe58fXlRAmJF7b75warqVsLEWg8a3jqP338rvGQsiZNDtFoecDgVRYmNzpn+T3RPkEIeb1bBtNxrcvEpvOzrMmsEopa+2YMMiHzq8Xthbie0kwN5iqUdOg9XN+GHoC+Kwt57oK9PLJ3X5+RK+tk5iZssyMq4B4WPeS2xE+zKnchBU+Kba57+1IeWXLr/e4qQ3Z3YFMKLAt2oJnutG/tPY6UO2BOo0uMtin/EAUYLPkXNIm60L93qB4Hif4ClwWgaQdfvMh8YBWGdEG815txxlA3Xv7HUWJ9MYR+rwd3CUf+XAxvb0Soisz7pIHNspaZSVS9RKt0qFJEzo61WF9yJmP32VVEIjWrHRvXSO99LPdAxpmI3N/PZOnU6pFQWp1lvRB28uolFEw5UfFkKXVq44Uu8YFcvpVn0QJCMMXnKjWhI=
  - secure: p0YxMPedTBifnjULBQVpRgxMmCqqzejJXOeyL7wy0jWHea7V+MRfwYRp96/znEn7qen9ZM9YMxp8X2ewPXv4E1C7fJjC5PofyxEm05wK2IqTEknCbDZIE349+S8rF5HrrrwABHuKE7JpkjwZtXvZXii04NQXutCLblpab2FUcrrPIZOC3MggIcuZHAseSOiSB9BRSB+JQIUKaYSexdCI99fPQf6mV1wsfA2CbESU//gZVcSlxC5ignFWyyALn9S8hoNAK9eYh3lTZkiaSX77vBiiLdSBaxCw1a7psZmNLShkD2XV7Ae3gq9zqPh643lzbde3NO1rqesqRa/3FNofFLGD2wiIXX453Do/dzzNw1E2Hq3om0HwjuMguGArQm0yOvb8iThavh4ek1CDvR0Tdq2PiiqcOHPSSe390uvufevmZ7sCNCxcvNoYJkjtcV6RXVlPDRK3fv2ZdWIAnn83Ctxb8ohcmPguPAaLJIUE0ytplNtbBvHeOM6nncU6L+o03Zq1W8315LX7epR2kI5p64DPIJGY77mgUfNj/QF9WQqsYmhZL5AOYVsY6O5uSTRIamqPdfEXrOKtfDUb8dFYLTt0BnkNRUulLzpeih4uPYhSUAGHqt0g6Fp5JKE9oGldkg+tjF+hSJqfYLNfvAgYlq1ognyhQvQN0KU2Y9htKF0=
